package com.example.model

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val flag: String,
    val nativeName: String,
    val greeting: String
) {
    UZ("uz", "O'zbekcha", "🇺🇿", "O'zbek", "Xush kelibsiz!"),
    EN("en", "English", "🇬🇧", "English", "Welcome!"),
    RU("ru", "Русский", "🇷🇺", "Русский", "Добро пожаловать!"),
    DE("de", "Deutsch", "🇩🇪", "Deutsch", "Willkommen!"),
    FR("fr", "Français", "🇫🇷", "Français", "Bienvenue!"),
    ES("es", "Español", "🇪🇸", "Español", "¡Bienvenido!"),
    TR("tr", "Türkçe", "🇹🇷", "Türkçe", "Hoş geldiniz!"),
    ZH("zh", "中文", "🇨🇳", "中文", "欢迎！"),
    JA("ja", "日本語", "🇯🇵", "日本語", "ようこそ！");

    companion object {
        var currentLanguage: AppLanguage
            get() = AppLanguageState.currentLanguage
            set(value) {
                AppLanguageState.currentLanguage = value
            }
    }
}

object AppLanguageState {
    var currentLanguage by mutableStateOf(AppLanguage.UZ)
}

val LocalAppLanguage = compositionLocalOf { AppLanguage.UZ }

@Composable
fun appString(key: String): String {
    val lang = LocalAppLanguage.current
    return AppStrings.get(key, lang)
}

object AppStrings {
    fun get(key: String, lang: AppLanguage = AppLanguageState.currentLanguage): String {
        return when (lang) {
            AppLanguage.EN -> translationsEn[key] ?: translationsUz[key] ?: key
            AppLanguage.RU -> translationsRu[key] ?: translationsUz[key] ?: key
            AppLanguage.DE -> translationsDe[key] ?: translationsEn[key] ?: key
            AppLanguage.FR -> translationsFr[key] ?: translationsEn[key] ?: key
            AppLanguage.ES -> translationsEs[key] ?: translationsEn[key] ?: key
            AppLanguage.TR -> translationsTr[key] ?: translationsUz[key] ?: key
            AppLanguage.ZH -> translationsZh[key] ?: translationsEn[key] ?: key
            AppLanguage.JA -> translationsJa[key] ?: translationsEn[key] ?: key
            AppLanguage.UZ -> translationsUz[key] ?: key
        }
    }

    private val translationsUz = mapOf(
        // App & Navigation
        "app_title" to "Buyuk Ipak Yo'li",
        "nav_discover" to "Kashf eting",
        "nav_map" to "GPS Xarita",
        "nav_booking" to "Zakaz",
        "nav_expenses" to "Xarajatlar",
        "nav_ar" to "AR Vision",
        "nav_offers" to "Takliflar",

        // Top Bar & Controls
        "select_language" to "Tilni Tanlang",
        "lang_dialog_sub" to "Xalqaro sayyohlar uchun 9 ta til",
        "search_placeholder" to "Obidalar, shahar va gidlarni qidirish...",
        "search_label" to "Qidiruv",
        "offline_mode" to "Oflayn Rejim",
        "dark_mode" to "Tungi Ko'rinish",
        "audio_guide" to "Milliy Audio Gid",
        "currency_calc" to "Valyuta & Byudjet",
        "sos_emergency" to "SOS Favqulodda Yordam",
        "back_button" to "Orqaga",

        // Home Hero & Categories
        "hero_title" to "O'zbekiston Bo'ylab Sehrli Sayohat",
        "hero_sub" to "Samarqand, Buxoro, Xiva va Toshkentning eng sara durdonalari",
        "cat_all" to "Barchasi",
        "cat_unesco" to "UNESCO Merosi",
        "cat_sacred" to "Muqaddas Qadamjolar",
        "cat_fortress" to "Ipak Yo'li Qal'alari",
        "cat_nature" to "Tabiat & Tog'lar",
        "cat_dining" to "Bozorlar & Taomlar",
        "crowd_low" to "Tinch va Qulay",
        "crowd_moderate" to "O'rtacha Gavjum",
        "crowd_high" to "Gavjum & Qaynoq",

        // Staff Booking Feature
        "staff_hero_badge" to "EKSKLYUZIV SAYYOHLIK XIZMATI",
        "staff_hero_title" to "Turistlarni Aylantirish Uchun Mas'ul Xodimga Zakaz Berish",
        "staff_hero_desc" to "Tarixiy obidalar (Registon, Ark, Ichan Qal'a) bo'yicha oliy toifali gidlar, VIP transfer va to'liq sayohat hamrohlari.",
        "staff_hero_btn" to "Mas'ul Xodim Zakaz Qilish  ➔",
        "staff_tab_catalog" to "Mas'ul Xodimlar",
        "staff_tab_orders" to "Mening Buyurtmalarim",
        "staff_top_badge" to "MAS'UL XODIMLAR & TURISTIK HAMROH",
        "staff_top_title" to "Ekskursiya & Zakaz",
        "staff_top_subtitle" to "Turistlarni O'zbekiston bo'ylab aylantirish, tarixiy obidalar ekskursiyasi va VIP transport uchun professional mas'ul xodimlarga buyurtma bering.",
        "staff_tab_staff" to "Mas'ul Xodimlar",
        "staff_tab_my_orders" to "Mening Buyurtmalarim",
        "orders_count_suffix" to "zakaz",
        "staff_online_badge" to "ONLINE MAS'UL XODIMLAR",
        "staff_rate_type" to "Soatbay yoki Kunlik",
        "staff_languages_tag" to "Ingliz, Rus, Turk, Fransuz, Nemis, Xitoy",
        "select_city" to "Shaharni tanlang",
        "city_all" to "Barchasi",
        "book_now" to "Zakaz berish  ➔",
        "call_staff" to "Qo'ng'iroq",
        "per_hour" to "soat",
        "per_day" to "kun",
        "licensed_staff" to "Litsenziyali Mas'ul Xodim",
        "order_code" to "Buyurtma Kodi",
        "assigned_staff" to "Biriktirilgan Xodim",
        "order_confirmed" to "Xodim Biriktirildi & Tasdiqlandi",
        "order_pending" to "Kutilmoqda",
        "order_ontheway" to "Xodim Manzilga Yo'lda",
        "order_completed" to "Muvaffaqiyatli Yakunlandi",
        "order_cancelled" to "Bekor Qilindi",
        "cancel_order" to "Bekor qilish",
        "no_active_orders" to "Hozircha faol buyurtmalar yo'q",
        "view_staff_catalog" to "Xodimlarni ko'rish  ➔",
        "booking_dialog_title" to "Mas'ul Xodimga Zakaz Berish",
        "tourist_name_label" to "Sayyohning Ismi",
        "tourist_phone_label" to "Telefon Raqami",
        "pickup_location_label" to "Kutib olish manzili (Mehmonxona/Aeroport)",
        "tour_duration_label" to "Davomiylik",
        "tourist_count_label" to "Sayyohlar soni",
        "confirm_booking_btn" to "Buyurtmani Tasdiqlash  ➔",
        "total_calc_price" to "Jami hisoblangan narx",

        // Expenses Tracker
        "expenses_title" to "Xarajatlar & Jonli Hisob",
        "deposit_balance" to "Depozit Qoldig'i",
        "total_spent" to "Jami Sarflangan",
        "add_expense" to "Yangi Xarajat Qo'shish",
        "top_up" to "Depozit To'ldirish",
        "exp_all" to "Barchasi",
        "exp_restaurant" to "Restoran & Taom",
        "exp_transport" to "VIP Transport & Haydovchi",
        "exp_hotel" to "Mehmonxona & Dam",
        "exp_tickets" to "Muzey & Chiptalar",
        "exp_shopping" to "Bozor & Suvenir",
        "exp_guide" to "Gid & Maxsus Servis",
        "receipt_label" to "Chek / Kvitansiya",

        // Offers & Services
        "offers_title" to "Xizmatlar & Maxsus Takliflar",
        "call_hotline" to "24/7 Dispetcherlik Qo'ng'iroq",
        "boutique_hotels" to "Boutique Mehmonxonalar",
        "national_cuisine" to "Milliy Taomlar & Choyxonalar",
        "private_fleet" to "VIP Avtopark & Transfer",
        "reserve_now" to "Band Qilish",

        // Registration & Welcome
        "welcome_title" to "Ipak Yo'liga Xush Kelibsiz",
        "registration_title" to "Sayyohni Ro'yxatdan O'tkazish",
        "reg_title" to "Ro'yxatdan o'tish",
        "reg_step_1_title" to "1. Ilova tilini tanlang",
        "reg_step_1_sub" to "O'zingizga qulay bo'lgan tilni belgilang",
        "reg_step_1_phone_title" to "2. Telefon raqamingiz",
        "reg_step_1_phone_sub" to "Siz bilan bog'lanish va xavfsizlik uchun kerak bo'ladi",
        "reg_phone_label" to "Telefon raqami",
        "reg_continue_btn" to "Davom etish  ➔",
        "reg_step_2_title" to "Ism va Familiyangizni kiriting",
        "reg_step_2_sub" to "Gid va xizmatlar sizga ism-sharifingiz bo'yicha murojaat qiladi",
        "reg_first_name" to "Ismingiz",
        "reg_first_name_hint" to "Masalan: Jasur",
        "reg_last_name" to "Familiyangiz",
        "reg_last_name_hint" to "Masalan: Aliyev",
        "reg_step_3_title" to "Gmail pochta manzilingiz",
        "reg_step_3_sub" to "Sayyohlik chiptalari va vaucherlar pochtangizga yuboriladi",
        "reg_email_label" to "Gmail / Elektron pochta",
        "reg_summary_title" to "RO'YXATDAN O'TISH XULOSASI",
        "reg_lang_label" to "Til",
        "reg_finish_btn" to "Ro'yxatdan o'tishni yakunlash  ✓",
        "reg_saving_title" to "Ma'lumotlaringizni saqlayapmiz...",
        "reg_seconds" to "soniya",
        "reg_loading" to "Yuklanmoqda...",
        "err_enter_phone" to "Iltimos, to'liq telefon raqamingizni kiriting",
        "err_enter_firstname" to "Iltimos, ismingizni kiriting",
        "err_enter_lastname" to "Iltimos, familiyangizni kiriting",
        "err_enter_email" to "Iltimos, to'g'ri Gmail manzilingizni kiriting",
        "saving_msg_1" to "Foydalanuvchi profili xavfsiz yaratilmoqda...",
        "saving_msg_2" to "Sayyohlik xaritalari va shaxsiy hisob sozlanmoqda...",
        "saving_msg_3" to "Barcha ma'lumotlar markaziy tizim va Telegramga yuborilmoqda...",
        "saving_msg_4" to "Muvaffaqiyatli saqlandi va Telegramga yetkazildi! Xush kelibsiz...",
        "full_name" to "To'liq Ism va Familiya",
        "country_origin" to "Davlat / Millat",
        "phone_number" to "Telefon Raqam",
        "passport_num" to "Pasport Raqami",
        "continue_btn" to "Sayohatni Boshlash  ➔",
        "skip_guest" to "Mehmon Sifatida Kirish",

        // SOS & Emergency
        "sos_title" to "SOS Favqulodda Yordam",
        "tourist_police" to "Turizm Politsiyasi (1173)",
        "medical_emergency" to "Tez Tibbiy Yordam (103)",
        "fire_service" to "Yong'in Xavfsizligi (101)",
        "send_sos" to "SOS Xabar Jo'natish",
        "sos_contacting_title" to "Siz bilan aloqaga chiqayapmiz...",
        "sos_contacting_desc" to "Dispetcherlik xizmati sizning koordinatangiz va SOS chaqiruvingizni qabul qildi. Operatorimiz 5 daqiqa ichida siz bilan bog'lanadi.",
        "sos_estimated_time" to "Kutilayotgan aloqa vaqti",
        "sos_active_status" to "SOS CHAQIRUV FAOL",
        "sos_telegram_sent" to "Telegram Botga yuborildi (Dispecher ID: 6089586932) ✓",
        "sos_cancel_emergency" to "Chaqiruvni yakunlash",
        "sos_keep_in_app" to "Ilovadan chiqmang, aloqa o'rnatilmoqda",
        "sos_minimize" to "Xaritaga qarash",
        "sos_subtitle" to "24/7 Tezkor Yordam & Jonli GPS",
        "sos_trigger_btn" to "🚨 SOS FAVQULODDA YORDAM CHAQIRISH",
        "sos_trigger_sub" to "Jonli GPS bilan dispetcherga zudlik bilan xabar yuborish",
        "sos_quick_call" to "Tezkor Favqulodda Qo'ng'iroqlar",
        "sos_direct_call_desc" to "Bir teginish orqali to'g'ridan-to'g'ri bog'lanish",
        "sos_call_ambulance" to "Tez Tibbiy Yordam (103)",
        "sos_call_police" to "Ichki Ishlar / Militsiya (102)",
        "sos_call_rescue" to "FVV Favqulodda Qutqaruv (112)",
        "sos_call_tourism_police" to "Turizm Xavfsizlik Politsiyasi (1173)",
        "sos_your_location" to "Sizning joylashuvingiz",
        "sos_close" to "Yopish",
        "sos_quick_sub" to "Call Center & GPS",
        "audio_quick_sub" to "Sharqona hikoyalar",
        "currency_quick_sub" to "Byudjet & Tips",
        "gps_live_fix" to "JONLI GPS (HAQIQIY KOORDINATA)",
        "gps_searching" to "GPS SIGNALI QIDIRILMOQDA...",
        "home_3_tariffs_title" to "3 XIL SAYOHAT TARIFLARI",
        "home_3_tariffs_sub" to "Hotel + 3 mahal taom + Shaxsiy Taxi + Cheklar",
        "tariff_all_btn" to "Barchasi ➔",
        "tariff_1_name" to "1-Tarif",
        "tariff_1_desc" to "2 kun (Samarqand 5 maskan)",
        "tariff_2_name" to "2-Tarif (VIP)",
        "tariff_2_desc" to "7 kun VIP Hotel & Taxi",
        "tariff_3_name" to "3-Tarif Grand",
        "tariff_3_desc" to "14 kun Butun O'zbekiston",
        "tariff_payment_note" to "💳 Karta orqali yoki 💵 Naqd to'lov • To'liq cheklar",
        "tariff_select_btn" to "Batafsil Tanlash ➔",
        "curated_bento_title" to "IPAK YO'LI SARALANGAN DURDONALARI",
        "iconic_wonders_title" to "TARIXIY DURDONALAR",
        "explore_3d_map" to "3D Xarita →",
        "bento_ai_camera_title" to "AI Kamera 1400",
        "bento_ai_camera_sub" to "Qadimgi Registon & Audio",
        "bento_surprise_title" to "AI Syurpriz Sayohat",
        "bento_surprise_sub" to "Tezkor Rejalashtirish",
        "bento_itinerary_title" to "Joriy Marshrut",
        "bento_itinerary_sub" to "3 maskan • 2 kun qoldi",
        "tariffs_screen_title" to "Sayohat Tariflari",
        "tariffs_screen_sub" to "3 xil qulay tarif • Karta yoki Naqd to'lov • Barcha cheklar",
        "tariffs_tab_packages" to "Tarif Paketlari (3 xil)",
        "tariffs_tab_receipts" to "Cheklar & Kvitansiyalar",
        "tariff_book_btn" to "Band Qilish & Chek Olish ➔",
        "tariff_booking_title" to "Tarifni Rasmiylashtirish",
        "tariff_payment_type" to "To'lov turi",
        "tariff_confirm_create_receipt" to "Tasdiqlash va Chek Yaratish  ✓",
        "unesco_crown_jewel" to "YUNESKO DURDONASI",
        "tourist_name_label" to "Sayyoh F.I.SH",
        "tourist_phone_label" to "Telefon raqami",
        "tourist_count_label" to "Sayyohlar soni",
        "ad_badge" to "REKLAMA • INSTAGRAM REEL",
        "ad_title" to "O'zbekiston Bo'ylab Eksklyuziv Video",
        "ad_desc" to "Samarqand, Registon va Ipak yo'lining betakror manzaralari. Maxsus video ko'rsatuvni Instagram Reel orqali tomosha qiling!",
        "ad_watch_btn" to "Reel'ni Tomosha Qilish ▶",
        "ad_share_btn" to "Ulashish ↗",
        "ad_stats_views" to "120K+ tomosha • Jonli kadrlar"
    )

    private val translationsEn = mapOf(
        // App & Navigation
        "app_title" to "Great Silk Road",
        "nav_discover" to "Discover",
        "nav_map" to "3D Map",
        "nav_booking" to "Book Staff",
        "nav_expenses" to "Expenses",
        "nav_ar" to "AR Vision",
        "nav_offers" to "Offers",

        // Top Bar & Controls
        "select_language" to "Select Language",
        "lang_dialog_sub" to "Supporting 9 international languages",
        "search_placeholder" to "Search monuments, cities & guides...",
        "search_label" to "Search",
        "offline_mode" to "Offline Mode",
        "dark_mode" to "Dark Mode",
        "audio_guide" to "Audio Tour",
        "currency_calc" to "Currency & Budget",
        "sos_emergency" to "SOS Emergency Help",
        "back_button" to "Back",

        // Home Hero & Categories
        "hero_title" to "Enchanting Journey Across Uzbekistan",
        "hero_sub" to "The finest treasures of Samarkand, Bukhara, Khiva and Tashkent",
        "cat_all" to "All Gems",
        "cat_unesco" to "UNESCO Heritage",
        "cat_sacred" to "Sacred Mosques",
        "cat_fortress" to "Silk Road Fortresses",
        "cat_nature" to "Alpine & Nature",
        "cat_dining" to "Bazaars & Dining",
        "crowd_low" to "Quiet & Peaceful",
        "crowd_moderate" to "Moderate Breeze",
        "crowd_high" to "Vibrant & Bustling",

        // Staff Booking Feature
        "staff_hero_badge" to "EXCLUSIVE TOURIST SERVICE",
        "staff_hero_title" to "Book a Dedicated Guide & Escort for Tourists",
        "staff_hero_desc" to "Top-tier licensed guides, VIP transportation and full concierge escorts across Samarkand, Bukhara, Khiva.",
        "staff_hero_btn" to "Book Dedicated Staff  ➔",
        "staff_tab_catalog" to "Staff Catalog",
        "staff_tab_orders" to "My Bookings",
        "staff_top_badge" to "LICENSED STAFF & TOUR ESCORT",
        "staff_top_title" to "Tours & Booking",
        "staff_top_subtitle" to "Book professional licensed guides, VIP transportation and curated historical tours across Uzbekistan.",
        "staff_tab_staff" to "Dedicated Staff",
        "staff_tab_my_orders" to "My Bookings",
        "orders_count_suffix" to "bookings",
        "staff_online_badge" to "ONLINE LICENSED STAFF",
        "staff_rate_type" to "Hourly or Full Day",
        "staff_languages_tag" to "English, Russian, Turkish, French, German, Chinese",
        "select_city" to "Select City",
        "city_all" to "All Cities",
        "book_now" to "Book Now  ➔",
        "call_staff" to "Call",
        "per_hour" to "hour",
        "per_day" to "day",
        "licensed_staff" to "Licensed Tour Staff",
        "order_code" to "Booking Code",
        "assigned_staff" to "Assigned Staff",
        "order_confirmed" to "Staff Assigned & Confirmed",
        "order_pending" to "Pending Confirmation",
        "order_ontheway" to "Staff En Route",
        "order_completed" to "Successfully Completed",
        "order_cancelled" to "Cancelled",
        "cancel_order" to "Cancel Booking",
        "no_active_orders" to "No active bookings yet",
        "view_staff_catalog" to "Browse Staff Catalog  ➔",
        "booking_dialog_title" to "Book Dedicated Tour Staff",
        "tourist_name_label" to "Tourist Full Name",
        "tourist_phone_label" to "Phone Number",
        "pickup_location_label" to "Pickup Address (Hotel/Airport)",
        "tour_duration_label" to "Duration",
        "tourist_count_label" to "Number of Tourists",
        "confirm_booking_btn" to "Confirm Booking  ➔",
        "total_calc_price" to "Total Estimated Price",

        // Expenses Tracker
        "expenses_title" to "Tourist Expense Tracker",
        "deposit_balance" to "Deposit Balance",
        "total_spent" to "Total Spent",
        "add_expense" to "Add New Expense",
        "top_up" to "Top Up Deposit",
        "exp_all" to "All Expenses",
        "exp_restaurant" to "Dining & Restaurants",
        "exp_transport" to "VIP Transport & Driver",
        "exp_hotel" to "Hotels & Stays",
        "exp_tickets" to "Museums & Tickets",
        "exp_shopping" to "Bazaars & Souvenirs",
        "exp_guide" to "Guide & Concierge",
        "receipt_label" to "Receipt / Voucher",

        // Offers & Services
        "offers_title" to "VIP Services & Exclusive Offers",
        "call_hotline" to "Call 24/7 Dispatch Hotline",
        "boutique_hotels" to "Boutique Heritage Hotels",
        "national_cuisine" to "National Dining & Teahouses",
        "private_fleet" to "VIP Fleet & Airport Transfer",
        "reserve_now" to "Reserve Now",

        // Registration & Welcome
        "welcome_title" to "Welcome to the Silk Road",
        "registration_title" to "Tourist Registration",
        "reg_title" to "Registration",
        "reg_step_1_title" to "1. Select App Language",
        "reg_step_1_sub" to "Choose your preferred language",
        "reg_step_1_phone_title" to "2. Your Phone Number",
        "reg_step_1_phone_sub" to "Required for contact, bookings and safety",
        "reg_phone_label" to "Phone Number",
        "reg_continue_btn" to "Continue  ➔",
        "reg_step_2_title" to "Enter your First & Last Name",
        "reg_step_2_sub" to "Guides and concierges will address you by your name",
        "reg_first_name" to "First Name",
        "reg_first_name_hint" to "e.g. John",
        "reg_last_name" to "Last Name",
        "reg_last_name_hint" to "e.g. Smith",
        "reg_step_3_title" to "Gmail / Email Address",
        "reg_step_3_sub" to "Tour tickets, itineraries and receipts will be sent here",
        "reg_email_label" to "Gmail / Email Address",
        "reg_summary_title" to "REGISTRATION SUMMARY",
        "reg_lang_label" to "Language",
        "reg_finish_btn" to "Complete Registration  ✓",
        "reg_saving_title" to "Saving your profile...",
        "reg_seconds" to "sec",
        "reg_loading" to "Loading...",
        "err_enter_phone" to "Please enter your full phone number",
        "err_enter_firstname" to "Please enter your first name",
        "err_enter_lastname" to "Please enter your last name",
        "err_enter_email" to "Please enter a valid Gmail / Email address",
        "saving_msg_1" to "Creating secure tourist profile...",
        "saving_msg_2" to "Setting up offline maps and personal account...",
        "saving_msg_3" to "Dispatching profile and tourist details to Telegram...",
        "saving_msg_4" to "Saved successfully & sent to Telegram! Welcome...",
        "full_name" to "Full Name",
        "country_origin" to "Country / Citizenship",
        "phone_number" to "Phone Number",
        "passport_num" to "Passport Number",
        "continue_btn" to "Start Journey  ➔",
        "skip_guest" to "Continue as Guest",

        // SOS & Emergency
        "sos_title" to "Emergency SOS Assistance",
        "tourist_police" to "Tourist Police (1173)",
        "medical_emergency" to "Medical Emergency (103)",
        "fire_service" to "Fire Department (101)",
        "send_sos" to "Send Emergency SOS",
        "sos_contacting_title" to "We are contacting you...",
        "sos_contacting_desc" to "Our dispatch center has received your coordinates and emergency request. An operator will contact you within 5 minutes.",
        "sos_estimated_time" to "Estimated contact time",
        "sos_active_status" to "EMERGENCY SOS ACTIVE",
        "sos_telegram_sent" to "Dispatched to Telegram Bot (Dispatcher ID: 6089586932) ✓",
        "sos_cancel_emergency" to "End Call / Cancel SOS",
        "sos_keep_in_app" to "Please stay in the app, connecting...",
        "sos_minimize" to "Minimize / View Map",
        "sos_subtitle" to "24/7 Rapid Emergency & Live GPS",
        "sos_trigger_btn" to "🚨 REQUEST EMERGENCY SOS",
        "sos_trigger_sub" to "Send live GPS coordinates to dispatcher immediately",
        "sos_quick_call" to "Quick Emergency Hotlines",
        "sos_direct_call_desc" to "One-tap direct dial to emergency response",
        "sos_call_ambulance" to "Medical Emergency (103)",
        "sos_call_police" to "Police Department (102)",
        "sos_call_rescue" to "Rescue & Disaster (112)",
        "sos_call_tourism_police" to "Tourist Security Police (1173)",
        "sos_your_location" to "Your current location",
        "sos_close" to "Close",
        "sos_quick_sub" to "Call Center & GPS",
        "audio_quick_sub" to "Stories & History",
        "currency_quick_sub" to "Budget & Tips",
        "gps_live_fix" to "LIVE ACCURATE GPS FIX",
        "gps_searching" to "SEARCHING GPS SIGNAL...",
        "home_3_tariffs_title" to "3 TRAVEL TARIFF PACKAGES",
        "home_3_tariffs_sub" to "Hotel + 3 Meals Daily + Private Taxi + Receipts",
        "tariff_all_btn" to "All ➔",
        "tariff_1_name" to "Tier 1",
        "tariff_1_desc" to "2 days (Samarkand 5 gems)",
        "tariff_2_name" to "Tier 2 (VIP)",
        "tariff_2_desc" to "7 days VIP Hotel & Taxi",
        "tariff_3_name" to "Tier 3 Grand",
        "tariff_3_desc" to "14 days Across Uzbekistan",
        "tariff_payment_note" to "💳 By Card or 💵 Cash • Official Receipts",
        "tariff_select_btn" to "Select Package ➔",
        "curated_bento_title" to "CURATED SILK ROAD BENTO",
        "iconic_wonders_title" to "ICONIC WONDERS",
        "explore_3d_map" to "Explore 3D Map →",
        "bento_ai_camera_title" to "AI Camera 1400",
        "bento_ai_camera_sub" to "Ancient Registan & Audio",
        "bento_surprise_title" to "AI Surprise Me",
        "bento_surprise_sub" to "Plan Instantly",
        "bento_itinerary_title" to "Current Itinerary",
        "bento_itinerary_sub" to "3 destinations • 2 days left",
        "tariffs_screen_title" to "Travel Tariffs",
        "tariffs_screen_sub" to "3 Curated Tariffs • Card or Cash • Official Receipts",
        "tariffs_tab_packages" to "Tariff Packages (3 Tiers)",
        "tariffs_tab_receipts" to "Receipts & Vouchers",
        "tariff_book_btn" to "Book Package & Get Receipt ➔",
        "tariff_booking_title" to "Confirm Tariff Booking",
        "tariff_payment_type" to "Payment Method",
        "tariff_confirm_create_receipt" to "Confirm & Generate Receipt  ✓",
        "unesco_crown_jewel" to "UNESCO CROWN JEWEL",
        "tourist_name_label" to "Tourist Full Name",
        "tourist_phone_label" to "Phone Number",
        "tourist_count_label" to "Number of Tourists",
        "ad_badge" to "AD • INSTAGRAM REEL",
        "ad_title" to "Exclusive Silk Road Video Journey",
        "ad_desc" to "Discover the breathtaking beauty of Samarkand, Registan, and Uzbekistan. Watch our exclusive promo video on Instagram Reel!",
        "ad_watch_btn" to "Watch Reel on Instagram ▶",
        "ad_share_btn" to "Share ↗",
        "ad_stats_views" to "120K+ Views • Live Footage"
    )

    private val translationsRu = mapOf(
        // App & Navigation
        "app_title" to "Великий Шелковый Путь",
        "nav_discover" to "Исследовать",
        "nav_map" to "3D Карта",
        "nav_booking" to "Заказ Гида",
        "nav_expenses" to "Расходы",
        "nav_ar" to "AR Видение",
        "nav_offers" to "Услуги",

        // Top Bar & Controls
        "select_language" to "Выберите Язык",
        "lang_dialog_sub" to "Поддержка 9 международных языков",
        "search_placeholder" to "Поиск памятников, городов и гидов...",
        "search_label" to "Поиск",
        "offline_mode" to "Офлайн Режим",
        "dark_mode" to "Темная Тема",
        "audio_guide" to "Аудиогид",
        "currency_calc" to "Валюта и Бюджет",
        "sos_emergency" to "SOS Экстренная Помощь",
        "back_button" to "Назад",

        // Home Hero & Categories
        "hero_title" to "Волшебное Путешествие по Узбекистану",
        "hero_sub" to "Лучшие жемчужины Самарканда, Бухары, Хивы и Ташкента",
        "cat_all" to "Все жемчужины",
        "cat_unesco" to "Наследие ЮНЕСКО",
        "cat_sacred" to "Святыни и Мечети",
        "cat_fortress" to "Крепости Шелкового Пути",
        "cat_nature" to "Природа и Горы",
        "cat_dining" to "Базары и Кухня",
        "crowd_low" to "Спокойно и Тихо",
        "crowd_moderate" to "Умеренно",
        "crowd_high" to "Многолюдно и Оживленно",

        // Staff Booking Feature
        "staff_hero_badge" to "ЭКСКЛЮЗИВНЫЙ ТУРИСТИЧЕСКИЙ СЕРВИС",
        "staff_hero_title" to "Заказ Ответственного Гида и Сопровождающего",
        "staff_hero_desc" to "Лицензированные гиды высшей категории, VIP-трансфер и консьерж-сопровождение по городам Узбекистана.",
        "staff_hero_btn" to "Заказать Персонального Гида  ➔",
        "staff_tab_catalog" to "Каталог Гидов",
        "staff_tab_orders" to "Мои Заказы",
        "staff_top_badge" to "ОТВЕТСТВЕННЫЕ ГИДЫ И СОПРОВОЖДЕНИЕ",
        "staff_top_title" to "Экскурсии и Заказ",
        "staff_top_subtitle" to "Закажите профессиональных гидов, VIP транспорт и увлекательные экскурсии по достопримечательностям Узбекистана.",
        "staff_tab_staff" to "Персонал и Гиды",
        "staff_tab_my_orders" to "Мои Заказы",
        "orders_count_suffix" to "заказа",
        "staff_online_badge" to "ГИДЫ ОНЛАЙН",
        "staff_rate_type" to "Почасово или На весь день",
        "staff_languages_tag" to "Русский, Английский, Турецкий, Французский",
        "select_city" to "Выберите город",
        "city_all" to "Все города",
        "book_now" to "Заказать  ➔",
        "call_staff" to "Позвонить",
        "per_hour" to "час",
        "per_day" to "день",
        "licensed_staff" to "Лицензированный специалист",
        "order_code" to "Код заказа",
        "assigned_staff" to "Назначенный специалист",
        "order_confirmed" to "Специалист назначен и подтвержден",
        "order_pending" to "В ожидании подтверждения",
        "order_ontheway" to "Специалист в пути",
        "order_completed" to "Успешно завершено",
        "order_cancelled" to "Отменено",
        "cancel_order" to "Отменить заказ",
        "no_active_orders" to "Пока нет активных заказов",
        "view_staff_catalog" to "Смотреть список гидов  ➔",
        "booking_dialog_title" to "Заказ туристического сопровождающего",
        "tourist_name_label" to "Имя туриста",
        "tourist_phone_label" to "Номер телефона",
        "pickup_location_label" to "Адрес встречи (Отель/Аэропорт)",
        "tour_duration_label" to "Длительность",
        "tourist_count_label" to "Количество туристов",
        "confirm_booking_btn" to "Подтвердить заказ  ➔",
        "total_calc_price" to "Итоговая стоимость",

        // Expenses Tracker
        "expenses_title" to "Расходы и Живой Счет",
        "deposit_balance" to "Баланс Депозита",
        "total_spent" to "Всего потрачено",
        "add_expense" to "Добавить расход",
        "top_up" to "Пополнить Депозит",
        "exp_all" to "Все расходы",
        "exp_restaurant" to "Рестораны и питание",
        "exp_transport" to "VIP Транспорт и Водитель",
        "exp_hotel" to "Отели и проживание",
        "exp_tickets" to "Музеи и билеты",
        "exp_shopping" to "Базары и сувениры",
        "exp_guide" to "Гид и консьерж",
        "receipt_label" to "Чек / Квитанция",

        // Offers & Services
        "offers_title" to "Услуги и Эксклюзивные Предложения",
        "call_hotline" to "Позвонить Диспетчеру 24/7",
        "boutique_hotels" to "Бутик-Отели",
        "national_cuisine" to "Национальная Кухня и Чайханы",
        "private_fleet" to "VIP Автопарк и Трансфер",
        "reserve_now" to "Забронировать",

        // Registration & Welcome
        "welcome_title" to "Добро пожаловать на Шелковый Путь",
        "registration_title" to "Регистрация Туриста",
        "reg_title" to "Регистрация",
        "reg_step_1_title" to "1. Выберите язык приложения",
        "reg_step_1_sub" to "Выберите удобный для вас язык",
        "reg_step_1_phone_title" to "2. Ваш номер телефона",
        "reg_step_1_phone_sub" to "Необходим для связи, бронирования и безопасности",
        "reg_phone_label" to "Номер телефона",
        "reg_continue_btn" to "Продолжить  ➔",
        "reg_step_2_title" to "Введите имя и фамилию",
        "reg_step_2_sub" to "Гиды и персонал будут обращаться к вам по имени",
        "reg_first_name" to "Имя",
        "reg_first_name_hint" to "Например: Александр",
        "reg_last_name" to "Фамилия",
        "reg_last_name_hint" to "Например: Иванов",
        "reg_step_3_title" to "Gmail / Электронная почта",
        "reg_step_3_sub" to "Билеты, ваучеры и квитанции будут отправлены на эту почту",
        "reg_email_label" to "Gmail / Электронная почта",
        "reg_summary_title" to "ИТОГИ РЕГИСТРАЦИИ",
        "reg_lang_label" to "Язык",
        "reg_finish_btn" to "Завершить регистрацию  ✓",
        "reg_saving_title" to "Сохраняем ваши данные...",
        "reg_seconds" to "сек",
        "reg_loading" to "Загрузка...",
        "err_enter_phone" to "Пожалуйста, введите полный номер телефона",
        "err_enter_firstname" to "Пожалуйста, введите ваше имя",
        "err_enter_lastname" to "Пожалуйста, введите вашу фамилию",
        "err_enter_email" to "Пожалуйста, введите корректный адрес Gmail",
        "saving_msg_1" to "Создание безопасного профиля туриста...",
        "saving_msg_2" to "Настройка офлайн-карт и личного кабинета...",
        "saving_msg_3" to "Отправка всех данных профиля диспетчеру в Telegram...",
        "saving_msg_4" to "Успешно сохранено и отправлено в Telegram! Добро пожаловать...",
        "full_name" to "Полное имя",
        "country_origin" to "Страна / Гражданство",
        "phone_number" to "Номер телефона",
        "passport_num" to "Номер паспорта",
        "continue_btn" to "Начать путешествие  ➔",
        "skip_guest" to "Продолжить как гость",

        // SOS & Emergency
        "sos_title" to "Экстренная Помощь SOS",
        "tourist_police" to "Туристическая Полиция (1173)",
        "medical_emergency" to "Скорая Помощь (103)",
        "fire_service" to "Пожарная Служба (101)",
        "send_sos" to "Отправить сигнал SOS",
        "sos_contacting_title" to "Мы связываемся с вами...",
        "sos_contacting_desc" to "Диспетчерская служба получила ваши координаты и сигнал помощи. Оператор свяжется с вами в течение 5 минут.",
        "sos_estimated_time" to "Ожидаемое время связи",
        "sos_active_status" to "SOS СИГНАЛ АКТИВЕН",
        "sos_telegram_sent" to "Отправлено диспетчеру в Telegram (ID: 6089586932) ✓",
        "sos_cancel_emergency" to "Завершить вызов / Отменить SOS",
        "sos_keep_in_app" to "Оставайтесь в приложении, устанавливается связь",
        "sos_minimize" to "Свернуть / Смотреть карту",
        "sos_subtitle" to "Круглосуточная помощь и GPS локация",
        "sos_trigger_btn" to "🚨 ВЫЗВАТЬ ЭКСТРЕННУЮ ПОМОЩЬ SOS",
        "sos_trigger_sub" to "Мгновенная отправка GPS-координат диспетчеру",
        "sos_quick_call" to "Экстренные Службы",
        "sos_direct_call_desc" to "Прямой вызов в одно касание",
        "sos_call_ambulance" to "Скорая Помощь (103)",
        "sos_call_police" to "Милиция / Полиция (102)",
        "sos_call_rescue" to "Служба Спасения МЧС (112)",
        "sos_call_tourism_police" to "Туристическая Полиция (1173)",
        "sos_your_location" to "Ваше местоположение",
        "sos_close" to "Закрыть",
        "sos_quick_sub" to "Call Center & GPS",
        "audio_quick_sub" to "Истории и легенды",
        "currency_quick_sub" to "Бюджет и советы",
        "gps_live_fix" to "ТОЧНЫЙ GPS-СИГНАЛ",
        "gps_searching" to "ПОИСК GPS-СИГНАЛА...",
        "home_3_tariffs_title" to "3 ТАРИФНЫХ ПАКЕТА ТУРОВ",
        "home_3_tariffs_sub" to "Отель + 3-раз. питание + Личное такси + Чеки",
        "tariff_all_btn" to "Все ➔",
        "tariff_1_name" to "1-Тариф",
        "tariff_1_desc" to "2 дня (Самарканд 5 мест)",
        "tariff_2_name" to "2-Тариф (VIP)",
        "tariff_2_desc" to "7 дней VIP Отель и Такси",
        "tariff_3_name" to "3-Тариф Гранд",
        "tariff_3_desc" to "14 дней Весь Узбекистан",
        "tariff_payment_note" to "💳 Картой или 💵 Наличными • Официальные чеки",
        "tariff_select_btn" to "Выбрать Пакет ➔",
        "curated_bento_title" to "ИЗБРАННЫЕ ШЕДЕВРЫ ШЕЛКОВОГО ПУТИ",
        "iconic_wonders_title" to "ЗНАМЕНИТЫЕ ЧУДЕСА",
        "explore_3d_map" to "3D Карта →",
        "bento_ai_camera_title" to "AI Камера 1400",
        "bento_ai_camera_sub" to "Древний Регистан и Аудио",
        "bento_surprise_title" to "AI Сюрприз Путешествие",
        "bento_surprise_sub" to "Мгновенный План",
        "bento_itinerary_title" to "Текущий Маршрут",
        "bento_itinerary_sub" to "3 направления • 2 дня осталось",
        "tariffs_screen_title" to "Туристические Тарифы",
        "tariffs_screen_sub" to "3 удобных тарифа • Картой или Наличными • Чеки",
        "tariffs_tab_packages" to "Пакеты Тарифов (3 вида)",
        "tariffs_tab_receipts" to "Чеки и Квитанции",
        "tariff_book_btn" to "Забронировать и Получить Чек ➔",
        "tariff_booking_title" to "Оформление Тарифа",
        "tariff_payment_type" to "Способ Оплаты",
        "tariff_confirm_create_receipt" to "Подтвердить и Создать Чек  ✓",
        "unesco_crown_jewel" to "ЖЕМЧУЖИНА ЮНЕСКО",
        "tourist_name_label" to "Ф.И.О. Туриста",
        "tourist_phone_label" to "Номер телефона",
        "tourist_count_label" to "Количество туристов",
        "ad_badge" to "РЕКЛАМА • INSTAGRAM REEL",
        "ad_title" to "Эксклюзивный видеотур по Узбекистану",
        "ad_desc" to "Потрясающие кадры Самарканда, Регистана и Великого шелкового пути. Смотрите наш промо-ролик в Instagram Reel!",
        "ad_watch_btn" to "Смотреть Reel в Instagram ▶",
        "ad_share_btn" to "Поделиться ↗",
        "ad_stats_views" to "120K+ просмотров • Живые кадры"
    )

    private val translationsDe = mapOf(
        "app_title" to "Große Seidenstraße",
        "nav_discover" to "Entdecken",
        "nav_map" to "3D Karte",
        "nav_booking" to "Guide Buchen",
        "nav_expenses" to "Ausgaben",
        "nav_ar" to "AR Vision",
        "nav_offers" to "Angebote",
        "select_language" to "Sprache wählen",
        "lang_dialog_sub" to "In 9 internationalen Sprachen",
        "search_placeholder" to "Denkmäler, Städte & Guides suchen...",
        "search_label" to "Suche",
        "offline_mode" to "Offline-Modus",
        "dark_mode" to "Dunkelmodus",
        "audio_guide" to "Audio-Guide",
        "currency_calc" to "Währung & Budget",
        "sos_emergency" to "SOS Notfallhilfe",
        "back_button" to "Zurück",
        "hero_title" to "Zauberhafte Reise durch Usbekistan",
        "hero_sub" to "Die schönsten Schätze von Samarkand, Buchara, Chiwa und Taschkent",
        "cat_all" to "Alle Schätze",
        "cat_unesco" to "UNESCO-Erbe",
        "cat_sacred" to "Heilige Moscheen",
        "cat_fortress" to "Festungen der Seidenstraße",
        "cat_nature" to "Natur & Gebirge",
        "cat_dining" to "Basare & Gastronomie",
        "staff_hero_badge" to "EXKLUSIVER TOURISTENSERVICE",
        "staff_hero_title" to "Persönlichen Guide & Begleiter für Touristen buchen",
        "staff_hero_desc" to "Staatlich geprüfte Guides, VIP-Fahrservice und Rundum-Begleitung in ganz Usbekistan.",
        "staff_hero_btn" to "Mitarbeiter buchen  ➔",
        "staff_tab_catalog" to "Mitarbeiter-Katalog",
        "staff_tab_orders" to "Meine Buchungen",
        "staff_top_badge" to "REISELEITER & BEGLEITUNG",
        "staff_top_title" to "Touren & Buchung",
        "staff_top_subtitle" to "Buchen Sie professionelle Reiseleiter und VIP-Transport in Usbekistan.",
        "staff_tab_staff" to "Reiseleiter",
        "staff_tab_my_orders" to "Meine Buchungen",
        "orders_count_suffix" to "Buchungen",
        "select_city" to "Stadt wählen",
        "city_all" to "Alle Städte",
        "book_now" to "Jetzt buchen  ➔",
        "call_staff" to "Anrufen",
        "per_hour" to "Stunde",
        "per_day" to "Tag",
        "expenses_title" to "Ausgaben & Live-Konto",
        "deposit_balance" to "Guthaben",
        "total_spent" to "Gesamtausgaben",
        "add_expense" to "Ausgabe hinzufügen",
        "top_up" to "Guthaben aufladen",
        "offers_title" to "VIP-Services & Angebote",
        "welcome_title" to "Willkommen auf der Seidenstraße",
        "registration_title" to "Touristen-Registrierung",
        "reg_title" to "Registrierung",
        "reg_step_1_title" to "1. App-Sprache wählen",
        "reg_step_1_sub" to "Wählen Sie Ihre bevorzugte Sprache",
        "reg_step_1_phone_title" to "2. Ihre Telefonnummer",
        "reg_step_1_phone_sub" to "Erforderlich für Kontakt und Sicherheit",
        "reg_phone_label" to "Telefonnummer",
        "reg_continue_btn" to "Weiter  ➔",
        "reg_step_2_title" to "Geben Sie Ihren Vor- und Nachnamen ein",
        "reg_step_2_sub" to "Reiseleiter sprechen Sie mit Ihrem Namen an",
        "reg_first_name" to "Vorname",
        "reg_first_name_hint" to "z.B. Lukas",
        "reg_last_name" to "Nachname",
        "reg_last_name_hint" to "z.B. Müller",
        "reg_step_3_title" to "Gmail / E-Mail-Adresse",
        "reg_step_3_sub" to "Tickets und Buchungsbelege werden hierhin gesendet",
        "reg_email_label" to "Gmail / E-Mail",
        "reg_summary_title" to "REGISTRIERUNGSÜBERSICHT",
        "reg_lang_label" to "Sprache",
        "reg_finish_btn" to "Registrierung abschließen  ✓",
        "reg_saving_title" to "Ihre Daten werden gespeichert...",
        "reg_seconds" to "Sek",
        "reg_loading" to "Wird geladen...",
        "err_enter_phone" to "Bitte geben Sie Ihre vollständige Telefonnummer ein",
        "err_enter_firstname" to "Bitte Vornamen eingeben",
        "err_enter_lastname" to "Bitte Nachnamen eingeben",
        "err_enter_email" to "Bitte geben Sie eine gültige E-Mail-Adresse ein",
        "saving_msg_1" to "Sicheres Profil wird erstellt...",
        "saving_msg_2" to "Karten und Konto werden eingerichtet...",
        "saving_msg_3" to "Sicherheitsschlüssel wird generiert...",
        "saving_msg_4" to "Erfolgreich gespeichert! Willkommen...",
        "full_name" to "Vollständiger Name",
        "continue_btn" to "Reise starten  ➔",
        "sos_title" to "SOS Notfallhilfe",
        "sos_contacting_title" to "Wir nehmen Kontakt mit Ihnen auf...",
        "sos_contacting_desc" to "Unsere Notrufzentrale hat Ihre Koordinaten empfangen. Ein Mitarbeiter kontaktiert Sie innerhalb von 5 Minuten.",
        "sos_estimated_time" to "Geschätzte Kontaktzeit",
        "sos_active_status" to "SOS-NOTRUF AKTIV",
        "sos_telegram_sent" to "An Telegram-Zentrale gesendet (ID: 6089586932) ✓",
        "sos_cancel_emergency" to "Notruf beenden",
        "sos_keep_in_app" to "Bitte in der App bleiben, Verbindung wird hergestellt",
        "sos_minimize" to "Minimieren / Karte ansehen"
    )

    private val translationsFr = mapOf(
        "app_title" to "Route de la Soie",
        "nav_discover" to "Découvrir",
        "nav_map" to "Carte 3D",
        "nav_booking" to "Réserver",
        "nav_expenses" to "Dépenses",
        "nav_ar" to "Vision RA",
        "nav_offers" to "Offres",
        "select_language" to "Choisir la langue",
        "lang_dialog_sub" to "En 9 langues internationales",
        "search_placeholder" to "Rechercher monuments, villes & guides...",
        "search_label" to "Recherche",
        "offline_mode" to "Mode Hors-ligne",
        "dark_mode" to "Mode Sombre",
        "audio_guide" to "Audioguide",
        "currency_calc" to "Devises & Budget",
        "sos_emergency" to "SOS Urgence",
        "back_button" to "Retour",
        "hero_title" to "Voyage Envoûtant en Ouzbékistan",
        "hero_sub" to "Les plus beaux joyaux de Samarcande, Boukhara, Khiva et Tachkent",
        "cat_all" to "Tous les joyaux",
        "cat_unesco" to "Patrimoine UNESCO",
        "cat_sacred" to "Mosquées Sacrées",
        "cat_fortress" to "Forteresses de la Soie",
        "cat_nature" to "Nature & Montagnes",
        "cat_dining" to "Bazaars & Gastronomie",
        "staff_hero_badge" to "SERVICE TOURISTIQUE EXCLUSIF",
        "staff_hero_title" to "Réserver un Guide & Accompagnateur pour Touristes",
        "staff_hero_desc" to "Guides certifiés, transport VIP et conciergerie privée à travers l'Ouzbékistan.",
        "staff_hero_btn" to "Réserver un Accompagnateur  ➔",
        "staff_tab_catalog" to "Catalogue Guides",
        "staff_tab_orders" to "Mes Réservations",
        "staff_top_badge" to "GUIDES OFFICIELS & ACCOMPAGNEMENT",
        "staff_top_title" to "Visites & Réservation",
        "staff_top_subtitle" to "Réservez des guides professionnels et un transport VIP en Ouzbékistan.",
        "staff_tab_staff" to "Guides & Personnel",
        "staff_tab_my_orders" to "Mes Réservations",
        "orders_count_suffix" to "commandes",
        "select_city" to "Choisir la ville",
        "city_all" to "Toutes les villes",
        "book_now" to "Réserver  ➔",
        "call_staff" to "Appeler",
        "per_hour" to "heure",
        "per_day" to "jour",
        "expenses_title" to "Dépenses Touristiques",
        "deposit_balance" to "Solde du Dépôt",
        "total_spent" to "Total Dépensé",
        "add_expense" to "Ajouter une dépense",
        "top_up" to "Recharger le Dépôt",
        "offers_title" to "Services VIP & Offres Spéciales",
        "welcome_title" to "Bienvenue sur la Route de la Soie",
        "registration_title" to "Enregistrement Touristique",
        "reg_title" to "Inscription",
        "reg_step_1_title" to "1. Choisissez la langue",
        "reg_step_1_sub" to "Choisissez votre langue préférée",
        "reg_step_1_phone_title" to "2. Votre numéro de téléphone",
        "reg_step_1_phone_sub" to "Nécessaire pour le contact et la sécurité",
        "reg_phone_label" to "Numéro de téléphone",
        "reg_continue_btn" to "Continuer  ➔",
        "reg_step_2_title" to "Entrez votre nom et prénom",
        "reg_step_2_sub" to "Les guides s'adresseront à vous par votre nom",
        "reg_first_name" to "Prénom",
        "reg_first_name_hint" to "ex. Jean",
        "reg_last_name" to "Nom de famille",
        "reg_last_name_hint" to "ex. Dupont",
        "reg_step_3_title" to "Gmail / Adresse e-mail",
        "reg_step_3_sub" to "Les billets et bons de réservation seront envoyés ici",
        "reg_email_label" to "Gmail / E-mail",
        "reg_summary_title" to "RÉSUMÉ DE L'INSCRIPTION",
        "reg_lang_label" to "Langue",
        "reg_finish_btn" to "Finaliser l'inscription  ✓",
        "reg_saving_title" to "Enregistrement de vos données...",
        "reg_seconds" to "sec",
        "reg_loading" to "Chargement...",
        "err_enter_phone" to "Veuillez saisir votre numéro complet",
        "err_enter_firstname" to "Veuillez entrer votre prénom",
        "err_enter_lastname" to "Veuillez entrer votre nom de famille",
        "err_enter_email" to "Veuillez saisir une adresse e-mail valide",
        "saving_msg_1" to "Création du profil sécurisé...",
        "saving_msg_2" to "Configuration des cartes et du compte...",
        "saving_msg_3" to "Génération des clés de sécurité...",
        "saving_msg_4" to "Enregistré avec succès ! Bienvenue...",
        "full_name" to "Nom complet",
        "continue_btn" to "Commencer le voyage  ➔",
        "sos_title" to "Assistance SOS Urgence",
        "sos_contacting_title" to "Nous vous contactons...",
        "sos_contacting_desc" to "Le centre d'urgence a reçu vos coordonnées. Un opérateur vous contactera dans les 5 minutes.",
        "sos_estimated_time" to "Temps d'attente estimé",
        "sos_active_status" to "APPEL SOS ACTIF",
        "sos_telegram_sent" to "Transmis au centre Telegram (ID: 6089586932) ✓",
        "sos_cancel_emergency" to "Terminer l'appel",
        "sos_keep_in_app" to "Veuillez rester dans l'application, connexion en cours",
        "sos_minimize" to "Réduire / Voir la carte"
    )

    private val translationsEs = mapOf(
        "app_title" to "Ruta de la Seda",
        "nav_discover" to "Descubrir",
        "nav_map" to "Mapa 3D",
        "nav_booking" to "Reservar",
        "nav_expenses" to "Gastos",
        "nav_ar" to "Visión RA",
        "nav_offers" to "Ofertas",
        "select_language" to "Seleccionar idioma",
        "lang_dialog_sub" to "En 9 idiomas internacionales",
        "search_placeholder" to "Buscar monumentos, ciudades y guías...",
        "search_label" to "Buscar",
        "offline_mode" to "Modo Offline",
        "dark_mode" to "Modo Oscuro",
        "audio_guide" to "Audioguía",
        "currency_calc" to "Moneda y Presupuesto",
        "sos_emergency" to "Ayuda SOS",
        "back_button" to "Atrás",
        "hero_title" to "Viaje Mágico por Uzbekistán",
        "hero_sub" to "Las mejores joyas de Samarcanda, Bujará, Jiva y Taskent",
        "cat_all" to "Todas las joyas",
        "cat_unesco" to "Patrimonio UNESCO",
        "cat_sacred" to "Mezquitas Sagradas",
        "cat_fortress" to "Fortalezas de la Seda",
        "cat_nature" to "Naturaleza y Montañas",
        "cat_dining" to "Bazares y Comida",
        "staff_hero_badge" to "SERVICIO TURÍSTICO EXCLUSIVO",
        "staff_hero_title" to "Reservar Guía y Acompañante para Turistas",
        "staff_hero_desc" to "Guías certificados, transporte VIP y acompañamiento completo en Uzbekistán.",
        "staff_hero_btn" to "Reservar Personal  ➔",
        "staff_tab_catalog" to "Catálogo de Guías",
        "staff_tab_orders" to "Mis Reservas",
        "staff_top_badge" to "GUÍAS OFICIALES Y ACOMPAÑAMIENTO",
        "staff_top_title" to "Tours y Reserva",
        "staff_top_subtitle" to "Reserve guías profesionales y transporte VIP en Uzbekistán.",
        "staff_tab_staff" to "Personal y Guías",
        "staff_tab_my_orders" to "Mis Reservas",
        "orders_count_suffix" to "pedidos",
        "select_city" to "Seleccionar ciudad",
        "city_all" to "Todas las ciudades",
        "book_now" to "Reservar  ➔",
        "call_staff" to "Llamar",
        "per_hour" to "hora",
        "per_day" to "día",
        "expenses_title" to "Gastos y Control en Vivo",
        "deposit_balance" to "Saldo del Depósito",
        "total_spent" to "Total Gastado",
        "add_expense" to "Agregar gasto",
        "top_up" to "Recargar Depósito",
        "offers_title" to "Servicios VIP y Ofertas",
        "welcome_title" to "Bienvenido a la Ruta de la Seda",
        "registration_title" to "Registro de Turista",
        "reg_title" to "Registro",
        "reg_step_1_title" to "1. Seleccione el idioma",
        "reg_step_1_sub" to "Elija su idioma preferido",
        "reg_step_1_phone_title" to "2. Su número de teléfono",
        "reg_step_1_phone_sub" to "Necesario para contacto y seguridad",
        "reg_phone_label" to "Número de teléfono",
        "reg_continue_btn" to "Continuar  ➔",
        "reg_step_2_title" to "Ingrese su nombre y apellido",
        "reg_step_2_sub" to "Los guías se dirigirán a usted por su nombre",
        "reg_first_name" to "Nombre",
        "reg_first_name_hint" to "ej. Carlos",
        "reg_last_name" to "Apellido",
        "reg_last_name_hint" to "ej. Garcia",
        "reg_step_3_title" to "Gmail / Correo electrónico",
        "reg_step_3_sub" to "Las entradas y comprobantes se enviarán aquí",
        "reg_email_label" to "Gmail / Correo electrónico",
        "reg_summary_title" to "RESUMEN DE REGISTRO",
        "reg_lang_label" to "Idioma",
        "reg_finish_btn" to "Completar registro  ✓",
        "reg_saving_title" to "Guardando sus datos...",
        "reg_seconds" to "seg",
        "reg_loading" to "Cargando...",
        "err_enter_phone" to "Por favor ingrese su número completo",
        "err_enter_firstname" to "Por favor ingrese su nombre",
        "err_enter_lastname" to "Por favor ingrese su apellido",
        "err_enter_email" to "Por favor ingrese un correo válido",
        "saving_msg_1" to "Creando perfil de turista seguro...",
        "saving_msg_2" to "Configurando mapas y cuenta personal...",
        "saving_msg_3" to "Estableciendo claves de seguridad...",
        "saving_msg_4" to "¡Guardado con éxito! Bienvenido...",
        "full_name" to "Nombre completo",
        "continue_btn" to "Comenzar viaje  ➔",
        "sos_title" to "Asistencia de Emergencia SOS",
        "sos_contacting_title" to "Nos estamos comunicando con usted...",
        "sos_contacting_desc" to "El centro de despacho ha recibido sus coordenadas. Un operador se comunicará con usted en 5 minutos.",
        "sos_estimated_time" to "Tiempo estimado de respuesta",
        "sos_active_status" to "SOS DE EMERGENCIA ACTIVO",
        "sos_telegram_sent" to "Enviado al centro Telegram (ID: 6089586932) ✓",
        "sos_cancel_emergency" to "Finalizar llamada",
        "sos_keep_in_app" to "Por favor permanezca en la app, conectando...",
        "sos_minimize" to "Minimizar / Ver mapa"
    )

    private val translationsTr = mapOf(
        "app_title" to "Büyük İpek Yolu",
        "nav_discover" to "Keşfet",
        "nav_map" to "3D Harita",
        "nav_booking" to "Rehber Tut",
        "nav_expenses" to "Harcamalar",
        "nav_ar" to "AR Görünüm",
        "nav_offers" to "Fırsatlar",
        "select_language" to "Dil Seçin",
        "lang_dialog_sub" to "9 uluslararası dilde",
        "search_placeholder" to "Tarihi yerleri, şehirleri ve rehberleri ara...",
        "search_label" to "Ara",
        "offline_mode" to "Çevrimdışı Mod",
        "dark_mode" to "Gece Modu",
        "audio_guide" to "Sesli Rehber",
        "currency_calc" to "Döviz ve Bütçe",
        "sos_emergency" to "SOS Acil Yardım",
        "back_button" to "Geri",
        "hero_title" to "Özbekistan'da Büyülü Yolculuk",
        "hero_sub" to "Semerkant, Buhara, Hiva ve Taşkent'in eşsiz incileri",
        "cat_all" to "Tümü",
        "cat_unesco" to "UNESCO Mirası",
        "cat_sacred" to "Kutsal Camiler",
        "cat_fortress" to "İpek Yolu Kaleleri",
        "cat_nature" to "Doğa ve Dağlar",
        "cat_dining" to "Pazarlar ve Lezzetler",
        "staff_hero_badge" to "ÖZEL TURİZM HİZMETİ",
        "staff_hero_title" to "Turistleri Gezdirmek İçin Özel Rehber Tut",
        "staff_hero_desc" to "Lisanslı uzman rehberler, VIP transfer ve tam kapsamlı seyahat refakati.",
        "staff_hero_btn" to "Rehber Tut  ➔",
        "staff_tab_catalog" to "Rehberler",
        "staff_tab_orders" to "Rezervasyonlarım",
        "staff_top_badge" to "REHBERLER VE TURİSTİK REFAKAT",
        "staff_top_title" to "Turlar ve Rezervasyon",
        "staff_top_subtitle" to "Özbekistan genelinde profesyonel rehberler ve VIP ulaşım için rezervasyon yapın.",
        "staff_tab_staff" to "Görevli Rehberler",
        "staff_tab_my_orders" to "Siparişlerim",
        "orders_count_suffix" to "sipariş",
        "select_city" to "Şehir seçin",
        "city_all" to "Tüm Şehirler",
        "book_now" to "Hemen Tut  ➔",
        "call_staff" to "Ara",
        "per_hour" to "saat",
        "per_day" to "gün",
        "expenses_title" to "Harcama Takibi & Bütçe",
        "deposit_balance" to "Depozito Bakiyesi",
        "total_spent" to "Toplam Harcanan",
        "add_expense" to "Harcama Ekle",
        "top_up" to "Bakiye Yükle",
        "offers_title" to "VIP Hizmetler ve Fırsatlar",
        "welcome_title" to "İpek Yolu'na Hoş Geldiniz",
        "registration_title" to "Turist Kaydı",
        "reg_title" to "Kayıt Ol",
        "reg_step_1_title" to "1. Uygulama dilini seçin",
        "reg_step_1_sub" to "Tercih ettiğiniz dili seçin",
        "reg_step_1_phone_title" to "2. Telefon numaranız",
        "reg_step_1_phone_sub" to "İletişim ve güvenlik için gereklidir",
        "reg_phone_label" to "Telefon numarası",
        "reg_continue_btn" to "Devam et  ➔",
        "reg_step_2_title" to "Adınızı ve Soyadınızı girin",
        "reg_step_2_sub" to "Rehberler size adınızla hitap edecektir",
        "reg_first_name" to "Adınız",
        "reg_first_name_hint" to "Örn: Mehmet",
        "reg_last_name" to "Soyadınız",
        "reg_last_name_hint" to "Örn: Yılmaz",
        "reg_step_3_title" to "Gmail / E-posta adresiniz",
        "reg_step_3_sub" to "Tur biletleri ve makbuzlar bu adrese gönderilecektir",
        "reg_email_label" to "Gmail / E-posta",
        "reg_summary_title" to "KAYIT ÖZETİ",
        "reg_lang_label" to "Dil",
        "reg_finish_btn" to "Kaydı Tamamla  ✓",
        "reg_saving_title" to "Bilgileriniz kaydediliyor...",
        "reg_seconds" to "sn",
        "reg_loading" to "Yükleniyor...",
        "err_enter_phone" to "Lütfen telefon numaranızı eksiksiz girin",
        "err_enter_firstname" to "Lütfen adınızı girin",
        "err_enter_lastname" to "Lütfen soyadınızı girin",
        "err_enter_email" to "Lütfen geçerli bir Gmail adresi girin",
        "saving_msg_1" to "Güvenli turist profili oluşturuluyor...",
        "saving_msg_2" to "Haritalar ve kişisel hesap yapılandırılıyor...",
        "saving_msg_3" to "Güvenlik anahtarı kuruluyor...",
        "saving_msg_4" to "Başarıyla kaydedildi! Hoş geldiniz...",
        "full_name" to "Ad Soyad",
        "continue_btn" to "Yolculuğa Başla  ➔",
        "sos_title" to "SOS Acil Yardım",
        "sos_contacting_title" to "Sizinle iletişime geçiyoruz...",
        "sos_contacting_desc" to "Acil çağrı merkezi koordinatlarınızı ve yardım çağrınızı aldı. Operatörümüz 5 dakika içinde sizinle iletişime geçecektir.",
        "sos_estimated_time" to "Tahmini bağlantı süresi",
        "sos_active_status" to "SOS ACİL ÇAĞRI AKTİF",
        "sos_telegram_sent" to "Telegram Merkezine iletildi (ID: 6089586932) ✓",
        "sos_cancel_emergency" to "Çağrıyı sonlandır",
        "sos_keep_in_app" to "Lütfen uygulamadan ayrılmayın, bağlanıyor...",
        "sos_minimize" to "Küçült / Haritaya bak",
        "home_3_tariffs_title" to "3 SEYAHAT TARİFESİ",
        "home_3_tariffs_sub" to "Otel + 3 Öğün Yemek + Özel Taksi + Faturalar",
        "tariff_all_btn" to "Tümü ➔",
        "tariff_1_name" to "1. Tarife",
        "tariff_1_desc" to "2 gün (Semerkant 5 mekan)",
        "tariff_2_name" to "2. Tarife (VIP)",
        "tariff_2_desc" to "7 gün VIP Otel & Taksi",
        "tariff_3_name" to "3. Tarife Grand",
        "tariff_3_desc" to "14 gün Tüm Özbekistan",
        "tariff_payment_note" to "💳 Kart veya 💵 Nakit Ödeme • Resmi Makbuzlar",
        "tariff_select_btn" to "Paketi Seç ➔",
        "curated_bento_title" to "İPEK YOLU SEÇKİN ESERLERİ",
        "iconic_wonders_title" to "TARİHİ HARİKALAR",
        "explore_3d_map" to "3D Harita →",
        "bento_ai_camera_title" to "AI Kamera 1400",
        "bento_ai_camera_sub" to "Tarihi Registan ve Sesli Rehber",
        "bento_surprise_title" to "AI Sürpriz Seyahat",
        "bento_surprise_sub" to "Anında Planla",
        "bento_itinerary_title" to "Mevcut Güzergah",
        "bento_itinerary_sub" to "3 rota • 2 gün kaldı",
        "tariffs_screen_title" to "Seyahat Tarifeleri",
        "tariffs_screen_sub" to "3 özel tarife • Kart veya Nakit • Faturalar",
        "tariffs_tab_packages" to "Tarife Paketleri (3 Çeşit)",
        "tariffs_tab_receipts" to "Fişler ve Makbuzlar",
        "tariff_book_btn" to "Rezervasyon Yap ve Fiş Al ➔",
        "tariff_booking_title" to "Tarife Rezervasyonu",
        "tariff_payment_type" to "Ödeme Türü",
        "tariff_confirm_create_receipt" to "Onayla ve Fiş Oluştur  ✓",
        "unesco_crown_jewel" to "UNESCO MİRASI",
        "tourist_name_label" to "Turist Adı Soyadı",
        "tourist_phone_label" to "Telefon Numarası",
        "tourist_count_label" to "Turist Sayısı",
        "ad_badge" to "REKLAM • INSTAGRAM REEL",
        "ad_title" to "Özbekistan Özel Video Turu",
        "ad_desc" to "Semerkant, Registan ve İpek Yolu'nun büyüleyici manzaraları. Özel tanıtım videomuzu Instagram Reel'de izleyin!",
        "ad_watch_btn" to "Reel'i İzle ▶",
        "ad_share_btn" to "Paylaş ↗",
        "ad_stats_views" to "120K+ Görüntülenme"
    )

    private val translationsZh = mapOf(
        "app_title" to "伟大丝绸之路",
        "nav_discover" to "探索",
        "nav_map" to "3D地图",
        "nav_booking" to "预订导游",
        "nav_expenses" to "旅行账单",
        "nav_ar" to "AR视觉",
        "nav_offers" to "特惠服务",
        "select_language" to "选择语言",
        "lang_dialog_sub" to "支持9种国际语言",
        "search_placeholder" to "搜索古迹、城市与向导...",
        "search_label" to "搜索",
        "offline_mode" to "离线模式",
        "dark_mode" to "深色模式",
        "audio_guide" to "语音导览",
        "currency_calc" to "汇率与预算",
        "sos_emergency" to "SOS紧急求救",
        "back_button" to "返回",
        "hero_title" to "乌兹别克斯坦梦幻之旅",
        "hero_sub" to "撒马尔罕、布哈拉、希瓦与塔什干的传世瑰宝",
        "cat_all" to "全部古迹",
        "cat_unesco" to "联合国世界遗产",
        "cat_sacred" to "神圣清真寺",
        "cat_fortress" to "丝路古堡",
        "cat_nature" to "山川自然",
        "cat_dining" to "集市与美食",
        "staff_hero_badge" to "专属旅游贵宾服务",
        "staff_hero_title" to "预约专业向导与全方位地接服务",
        "staff_hero_desc" to "高级认证历史向导、VIP专车接送及全天候贴心伴游。",
        "staff_hero_btn" to "立即预约专属人员  ➔",
        "staff_tab_catalog" to "向导名录",
        "staff_tab_orders" to "我的订单",
        "staff_top_badge" to "持证导游与专属陪同",
        "staff_top_title" to "导游与预订",
        "staff_top_subtitle" to "预订专业持证导游、VIP专车及乌兹别克斯坦深度文化游览服务。",
        "staff_tab_staff" to "专属导游人员",
        "staff_tab_my_orders" to "我的预订",
        "orders_count_suffix" to "订单",
        "select_city" to "选择城市",
        "city_all" to "所有城市",
        "book_now" to "立即预订  ➔",
        "call_staff" to "呼叫",
        "per_hour" to "小时",
        "per_day" to "天",
        "expenses_title" to "旅行支出与实时账单",
        "deposit_balance" to "充值余额",
        "total_spent" to "总支出",
        "add_expense" to "添加支出",
        "top_up" to "充值",
        "offers_title" to "VIP专属特惠与服务",
        "welcome_title" to "欢迎来到丝绸之路",
        "registration_title" to "游客登记",
        "reg_title" to "注册",
        "reg_step_1_title" to "1. 选择应用语言",
        "reg_step_1_sub" to "选择您偏好的语言",
        "reg_step_1_phone_title" to "2. 您的电话号码",
        "reg_step_1_phone_sub" to "用于联系、预订与安全保障",
        "reg_phone_label" to "电话号码",
        "reg_continue_btn" to "继续  ➔",
        "reg_step_2_title" to "请输入您的姓名",
        "reg_step_2_sub" to "导游与工作人员将用该姓名称呼您",
        "reg_first_name" to "名",
        "reg_first_name_hint" to "例如：明",
        "reg_last_name" to "姓",
        "reg_last_name_hint" to "例如：王",
        "reg_step_3_title" to "Gmail / 电子邮件",
        "reg_step_3_sub" to "旅游门票、行程单及收据将发送至此邮箱",
        "reg_email_label" to "Gmail / 电子邮件",
        "reg_summary_title" to "注册信息概览",
        "reg_lang_label" to "语言",
        "reg_finish_btn" to "完成注册  ✓",
        "reg_saving_title" to "正在保存您的信息...",
        "reg_seconds" to "秒",
        "reg_loading" to "加载中...",
        "err_enter_phone" to "请输入完整的电话号码",
        "err_enter_firstname" to "请输入您的名字",
        "err_enter_lastname" to "请输入您的姓氏",
        "err_enter_email" to "请输入有效的电子邮箱",
        "saving_msg_1" to "正在安全创建游客档案...",
        "saving_msg_2" to "正在配置离线地图及个人账户...",
        "saving_msg_3" to "正在生成安全密钥...",
        "saving_msg_4" to "保存成功！欢迎加入...",
        "full_name" to "姓名",
        "continue_btn" to "开启旅程  ➔",
        "sos_title" to "SOS紧急救助",
        "sos_contacting_title" to "我们正在与您取得联系...",
        "sos_contacting_desc" to "应急调度中心已收到您的实时位置与救助请求。客服人员将在5分钟内与您联系。",
        "sos_estimated_time" to "预计连线时间",
        "sos_active_status" to "SOS 紧急呼救进行中",
        "sos_telegram_sent" to "已发送至Telegram调度系统 (ID: 6089586932) ✓",
        "sos_cancel_emergency" to "结束呼叫 / 取消SOS",
        "sos_keep_in_app" to "请留在应用内，正在建立连接...",
        "sos_minimize" to "最小化 / 查看地图",
        "home_3_tariffs_title" to "3种旅游套餐",
        "home_3_tariffs_sub" to "酒店 + 每日三餐 + 专属出租车 + 正规收据",
        "tariff_all_btn" to "查看全部 ➔",
        "tariff_1_name" to "1档套餐",
        "tariff_1_desc" to "2天（撒马尔罕5大景点）",
        "tariff_2_name" to "2档 (VIP)",
        "tariff_2_desc" to "7天 VIP酒店与专车",
        "tariff_3_name" to "3档 豪华全景",
        "tariff_3_desc" to "14天 乌兹别克斯坦全境",
        "tariff_payment_note" to "💳 刷卡或 💵 现金支付 • 正规凭证",
        "tariff_select_btn" to "选择套餐 ➔",
        "curated_bento_title" to "丝绸之路精选锦集",
        "iconic_wonders_title" to "传世奇迹",
        "explore_3d_map" to "探索3D地图 →",
        "bento_ai_camera_title" to "AI古景相机 1400",
        "bento_ai_camera_sub" to "古代雷吉斯坦与语音",
        "bento_surprise_title" to "AI惊喜之旅",
        "bento_surprise_sub" to "立即规划",
        "bento_itinerary_title" to "当前行程",
        "bento_itinerary_sub" to "3个目的地 • 剩余2天",
        "tariffs_screen_title" to "旅游套餐资费",
        "tariffs_screen_sub" to "3种优选套餐 • 刷卡或现金 • 正规发票收据",
        "tariffs_tab_packages" to "套餐方案 (3种)",
        "tariffs_tab_receipts" to "收据与凭证",
        "tariff_book_btn" to "立即预订并生成收据 ➔",
        "tariff_booking_title" to "确认套餐预订",
        "tariff_payment_type" to "支付方式",
        "tariff_confirm_create_receipt" to "确认并生成电子收据  ✓",
        "unesco_crown_jewel" to "联合国教科文组织瑰宝",
        "tourist_name_label" to "游客姓名",
        "tourist_phone_label" to "联系电话",
        "tourist_count_label" to "出行人数",
        "ad_badge" to "广告 • INSTAGRAM REEL",
        "ad_title" to "乌兹别克斯坦专属视觉之旅",
        "ad_desc" to "探索撒马尔罕、雷吉斯坦与丝绸之路的绝美风光。在Instagram Reel观看官方宣传视频！",
        "ad_watch_btn" to "在Instagram观看Reel ▶",
        "ad_share_btn" to "分享 ↗",
        "ad_stats_views" to "12万+次播放 • 实时纪实"
    )

    private val translationsJa = mapOf(
        "app_title" to "大いなるシルクロード",
        "nav_discover" to "発見",
        "nav_map" to "3D地図",
        "nav_booking" to "ガイド予約",
        "nav_expenses" to "旅行支出",
        "nav_ar" to "ARビジョン",
        "nav_offers" to "おすすめ",
        "select_language" to "言語を選択",
        "lang_dialog_sub" to "9つの国際言語に対応",
        "search_placeholder" to "遺跡、都市、ガイドを検索...",
        "search_label" to "検索",
        "offline_mode" to "オフラインモード",
        "dark_mode" to "ダークモード",
        "audio_guide" to "音声ガイド",
        "currency_calc" to "通貨＆予算",
        "sos_emergency" to "SOS緊急ヘルプ",
        "back_button" to "戻る",
        "hero_title" to "ウズベキスタン魅惑の旅",
        "hero_sub" to "サマルカンド、ブハラ、ヒヴァ、タシュケントの至宝",
        "cat_all" to "すべて",
        "cat_unesco" to "ユネスコ世界遺産",
        "cat_sacred" to "聖なるモスク",
        "cat_fortress" to "シルクロードの要塞",
        "cat_nature" to "自然と山岳",
        "cat_dining" to "バザールと名物料理",
        "staff_hero_badge" to "プレミアム専属観光サービス",
        "staff_hero_title" to "観光客向け専属ガイド＆アテンド予約",
        "staff_hero_desc" to "国家公認ガイド、VIP送迎車、フルサポートのコンシェルジュ。",
        "staff_hero_btn" to "専属ガイドを予約する  ➔",
        "staff_tab_catalog" to "ガイド一覧",
        "staff_tab_orders" to "マイ予約",
        "staff_top_badge" to "専属ガイド＆同行サービス",
        "staff_top_title" to "ツアー＆予約",
        "staff_top_subtitle" to "ウズベキスタン全土でのプロガイド、VIP送迎、歴史名所ツアーをご予約いただけます。",
        "staff_tab_staff" to "専属ガイド一覧",
        "staff_tab_my_orders" to "マイ予約",
        "orders_count_suffix" to "件の予約",
        "select_city" to "都市を選択",
        "city_all" to "全都市",
        "book_now" to "予約する  ➔",
        "call_staff" to "電話する",
        "per_hour" to "時間",
        "per_day" to "日",
        "expenses_title" to "旅行支出＆リアルタイム会計",
        "deposit_balance" to "デポジット残高",
        "total_spent" to "総支出",
        "add_expense" to "支出を追加",
        "top_up" to "チャージ",
        "offers_title" to "VIPサービス＆限定プラン",
        "welcome_title" to "シルクロードへようこそ",
        "registration_title" to "旅行者登録",
        "reg_title" to "登録",
        "reg_step_1_title" to "1. アプリの言語を選択",
        "reg_step_1_sub" to "ご希望の言語を選択してください",
        "reg_step_1_phone_title" to "2. お電話番号",
        "reg_step_1_phone_sub" to "連絡、予約、および安全確認に必要です",
        "reg_phone_label" to "電話番号",
        "reg_continue_btn" to "次へ進む  ➔",
        "reg_step_2_title" to "お名前（氏名）を入力してください",
        "reg_step_2_sub" to "ガイドやスタッフがお客様のお名前でお呼びします",
        "reg_first_name" to "名",
        "reg_first_name_hint" to "例: 太郎",
        "reg_last_name" to "姓",
        "reg_last_name_hint" to "例: 田中",
        "reg_step_3_title" to "Gmail / メールアドレス",
        "reg_step_3_sub" to "ツアーチケットや予約確認書がこのアドレスに送信されます",
        "reg_email_label" to "Gmail / メールアドレス",
        "reg_summary_title" to "登録内容の確認",
        "reg_lang_label" to "言語",
        "reg_finish_btn" to "登録を完了する  ✓",
        "reg_saving_title" to "情報を保存しています...",
        "reg_seconds" to "秒",
        "reg_loading" to "読み込み中...",
        "err_enter_phone" to "完全な電話番号を入力してください",
        "err_enter_firstname" to "名を入力してください",
        "err_enter_lastname" to "姓を入力してください",
        "err_enter_email" to "有効なメールアドレスを入力してください",
        "saving_msg_1" to "旅行者プロファイルを安全に作成中...",
        "saving_msg_2" to "オフラインマップとアカウントを設定中...",
        "saving_msg_3" to "セキュリティキーを生成中...",
        "saving_msg_4" to "正常に保存されました！ようこそ...",
        "full_name" to "氏名",
        "continue_btn" to "旅を始める  ➔",
        "sos_title" to "SOS緊急サポート",
        "sos_contacting_title" to "現在、ご連絡を差し上げております...",
        "sos_contacting_desc" to "緊急指令センターがお客様の位置情報と要請を受信しました。オペレーターが5分以内にご連絡いたします。",
        "sos_estimated_time" to "連絡予定時間",
        "sos_active_status" to "SOS 緊急対応中",
        "sos_telegram_sent" to "Telegram指令センターへ送信完了 (ID: 6089586932) ✓",
        "sos_cancel_emergency" to "通話を終了 / SOS解除",
        "sos_keep_in_app" to "アプリを開いたままお待ちください。接続中です...",
        "sos_minimize" to "最小化 / 地図を確認",
        "home_3_tariffs_title" to "3つの旅行プラン",
        "home_3_tariffs_sub" to "ホテル + 3食付き + 専用タクシー + 領収書",
        "tariff_all_btn" to "すべて ➔",
        "tariff_1_name" to "プラン1",
        "tariff_1_desc" to "2日間（サマルカンド5名所）",
        "tariff_2_name" to "プラン2 (VIP)",
        "tariff_2_desc" to "7日間 VIPホテル＆タクシー",
        "tariff_3_name" to "プラン3 グランド",
        "tariff_3_desc" to "14日間 ウズベキスタン周遊",
        "tariff_payment_note" to "💳 カードまたは 💵 現金決済 • 公式領収書",
        "tariff_select_btn" to "プランを選ぶ ➔",
        "curated_bento_title" to "シルクロード特選コレクション",
        "iconic_wonders_title" to "歴史的遺産",
        "explore_3d_map" to "3Dマップを見る →",
        "bento_ai_camera_title" to "AIカメラ 1400",
        "bento_ai_camera_sub" to "古代レギスタン＆音声",
        "bento_surprise_title" to "AIサプライズ旅",
        "bento_surprise_sub" to "即時プランニング",
        "bento_itinerary_title" to "現在の旅程",
        "bento_itinerary_sub" to "3箇所の名所 • 残り2日",
        "tariffs_screen_title" to "旅行プラン・料金",
        "tariffs_screen_sub" to "3つの厳選プラン • カードまたは現金 • 公式領収書",
        "tariffs_tab_packages" to "料金プラン (3種類)",
        "tariffs_tab_receipts" to "領収書・明細",
        "tariff_book_btn" to "予約して領収書を発行 ➔",
        "tariff_booking_title" to "プラン予約手続き",
        "tariff_payment_type" to "お支払い方法",
        "tariff_confirm_create_receipt" to "確認して領収書を発行  ✓",
        "unesco_crown_jewel" to "ユネスコ世界遺産",
        "tourist_name_label" to "お名前",
        "tourist_phone_label" to "電話番号",
        "tourist_count_label" to "人数",
        "ad_badge" to "広告 • INSTAGRAM REEL",
        "ad_title" to "ウズベキスタン特別映像ツアー",
        "ad_desc" to "サマルカンド、レギスタン、シルクロードの絶景。Instagram Reelで特別プロモーション映像をご覧ください！",
        "ad_watch_btn" to "InstagramでReelを見る ▶",
        "ad_share_btn" to "共有 ↗",
        "ad_stats_views" to "12万回以上再生 • 臨場感あふれる映像"
    )
}
